### ISSUE TITLE
アドレスは16進数40桁

### ISSUE THREAD

**Issue by dumblepy** [frodo821/valiant-wallet#2]
https://github.com/frodo821/valiant-wallet/blob/master/src/valiant_wallet/account.nim#L39-L40

先頭の0xは無視される
https://github.com/ChainSafe/web3.js/blob/3.x/packages/web3-utils/src/utils.js#L87-L121

**Comment by frodo821** [comment]
@itsumura-h 対応しましたのでクローズします。
